### ISSUE TITLE
version update

### ISSUE THREAD

**Issue by fish-uncle** [apitable/apitable#1024]
I successfully installed v0.18.0-alpha before_ eight hundred and eighty-eight

And deleted the container through Docker

But when I install v0.22.0-alpha_ one thousand four hundred and fifty-three

He reported an error
[apitable.csv](https://github.com/apitable/apitable/files/11949751/apitable.csv)

What do I need to do

**Comment by fish-uncle** [comment]
[apitable (2).csv](https://github.com/apitable/apitable/files/11949994/apitable.2.csv)

**Comment by fish-uncle** [comment]
```
services:
  cherry:
    environment:
      MAIL_ENABLED: "true"
      MAIL_HOST: "smtp.163.com"
      MAIL_PASSWORD: "****"
      MAIL_PORT: "465"
      MAIL_USERNAME: "****"
      PUBLIC_URL: "****"
      SERVER_DOMAIN: "****"
      CALLBACK_DOMAIN: "****"	
    image: apitable/all-in-one:v0.22.0-alpha_1453
    container_name: apitable
    restart: unless-stopped
    ports:
      - 7088:80
    volumes:
      - ./data:/apitable
 ```
