### ISSUE TITLE
fix: arm64 room-server missing .lua and .proto files

### ISSUE THREAD

**Issue by networkhermit** [apitable/apitable#1107]
**Describe the bug**

After [enabling the experimental multi-arch build for linux/amd64 and linux/arm64](https://github.com/apitable/apitable/pull/1103), we find that the arm64 room-server can't start due to missing .lua and .proto files.

The root cause could be the nextjs assets copying procedure breaks in slow arm64 image build due to qemu emulation.

```text
apitable-room-server-1        | Error: ENOENT: no such file or directory, open ‘/app/packages/room-server/dist/shared/helpers/list.lock.lua’
apitable-room-server-1        |     at Object.openSync (node:fs:585:3)
apitable-room-server-1        |     at Object.readFileSync (node:fs:453:35)
apitable-room-server-1        |     at Object.<anonymous> (/app/packages/room-server/src/shared/helpers/redis.lock.ts:24:21)
apitable-room-server-1        |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
apitable-room-server-1        |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
apitable-room-server-1        |     at Module.load (node:internal/modules/cjs/loader:981:32)
apitable-room-server-1        |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
apitable-room-server-1        |     at Module.require (node:internal/modules/cjs/loader:1005:19)
apitable-room-server-1        |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
apitable-room-server-1        |     at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:101:39)
```

The amd64 image don't have the metioned problem, and mounting the .lua and .proto files exported from amd64 image in docker-compose.yaml makes room-server start successfully.

```yaml
  room-server:
    image: ${IMAGE_REGISTRY}/${IMAGE_ROOM_SERVER}
    pull_policy: ${IMAGE_PULL_POLICY:-if_not_present}
    restart: always
    expose:
      - "3333"
      - "3334"
      - "3001"
      - "3002"
      - "3006"
      - "3005"
      - "3007"
    env_file:
      - "${ENV_FILE:-.env}"
    environment:
      - TZ=${TIMEZONE}
      - NODE_ENV=${ENV}
      - NODE_OPTIONS=--max-old-space-size=2048 --max-http-header-size=80000
      - API_MAX_MODIFY_RECORD_COUNTS=${API_MAX_MODIFY_RECORD_COUNTS:-30}
      - INSTANCE_MAX_MEMORY=4096M
      - ENABLE_SOCKET=true
    networks:
      - apitable
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - source: ./list.lock.lua
        target: /app/packages/room-server/dist/shared/helpers/list.lock.lua
        type: bind
      - source: ./BackendServingService.proto
        target: /app/packages/room-server/dist/grpc/generated/serving/BackendServingService.proto
        type: bind
      - source: ./RoomServingService.proto
        target: /app/packages/room-server/dist/grpc/generated/serving/RoomServingService.proto
        type: bind
      - source: ./SocketServingService.proto
        target: /app/packages/room-server/dist/grpc/generated/serving/SocketServingService.proto
        type: bind
      - source: ./Core.proto
        target: /app/packages/room-server/dist/grpc/generated/common/Core.proto
        type: bind
```

**To Reproduce**
1. Just running `docker compose up -d` from the repo root in arm64 linux.

**Expected behavior**
Room server starts successfully.
