### ISSUE TITLE
question: Running apitable in swarm-mode

### ISSUE THREAD

**Issue by jakob1379** [apitable/apitable#1264]
Hello everyone,

I'm exploring the option of running Apitable in a Docker Swarm, which seems to be a good fit for smaller teams. This way, we can easily scale different components based on our needs. However, I'm running into an issue with the WebSocket, which can't connect natively due to Docker's load balancer.

What I Need Help With:
I would appreciate any assistance in creating a "textbook example" of a docker-compose.yaml file that integrates Traefik. I've tried different approaches to enable Traefik for the room-server and also attempted to establish connections with other services via Traefik using sticky sessions. Unfortunately, I've not been successful so far.

Any advice or examples would be greatly appreciated.

Here's what I come up with so far, this requires a onetime hand-held start with the init-services which is doable.

<details>
  <summary>Click to expand docker-compose.yml </summary>
  
```yml
version: "3.9"

services:
  web-server:
    image: ${IMAGE_REGISTRY}/${IMAGE_WEB_SERVER}
    env_file:
      - "${ENV_FILE:-.env}"
    networks:
      - apitable

  imageproxy-server:
    image: ${IMAGE_REGISTRY}/${IMAGE_IMAGEPROXY_SERVER}
    deploy:
      replicas: 1
    environment:
      - TZ=${TIMEZONE}
      - BASEURL=${AWS_ENDPOINT}
    networks:
      - apitable

  backend-server:
    image: ${IMAGE_REGISTRY}/${IMAGE_BACKEND_SERVER}
    deploy:
      restart_policy:
        condition: none
      replicas: 1
    env_file:
      - "${ENV_FILE:-.env}"
    environment:
      - TZ=${TIMEZONE}
      - DEFAULT_TIME_ZONE=${TIMEZONE}
    networks:
      - apitable

  room-server:
    image: ${IMAGE_REGISTRY}/${IMAGE_ROOM_SERVER}
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.room-server.loadbalancer.sticky.cookie=true"
        - "traefik.http.routers.room-server.rule=Host(`apitable-roomserver.traefik.me`)"
        - "traefik.http.routers.room-server.entrypoints=web"
        - "traefik.http.routers.room-server.tls=true"
        - "traefik.http.routers.room-server.entrypoints=websecure"
      restart_policy:
        condition: none
    env_file:
      - "${ENV_FILE:-.env}"
    environment:
      - TZ=${TIMEZONE}
      - NODE_ENV=${ENV}
      - NODE_OPTIONS=--max-old-space-size=2048 --max-http-header-size=80000
      - API_MAX_MODIFY_RECORD_COUNTS=${API_MAX_MODIFY_RECORD_COUNTS:-30}
      - INSTANCE_MAX_MEMORY=4096M
      - ENABLE_SOCKET=true
    networks:
      - apitable
      - traefik

  databus-server:
    image: ${IMAGE_REGISTRY}/${IMAGE_DATABUS_SERVER}
    restart: always
    env_file:
      - "${ENV_FILE:-.env}"
    environment:
      - TZ=${TIMEZONE}
    networks:
      - apitable

  # Third Party Dockers
  gateway:
    image: ${IMAGE_REGISTRY}/${IMAGE_GATEWAY}
    environment:
      - TZ=${TIMEZONE}
    networks:
      - apitable
      - traefik
    deploy:
      restart_policy:
        condition: none
      replicas: 0
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.apitable.rule=Host(`apitable.traefik.me`)"
        - "traefik.http.routers.apitable.entrypoints=websecure"
        - "traefik.http.routers.apitable.tls=true"
        - "traefik.http.services.apitable.loadbalancer.server.port=80"

  minio:
    image: ${IMAGE_MINIO}
    restart: always
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      - TZ=${TIMEZONE}
    networks:
      - apitable

  redis:
    image: ${IMAGE_REDIS}
    command:
      - "redis-server"
      - "--appendonly"
      - "yes"
      - "--requirepass"
      - "${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    environment:
      - TZ=${TIMEZONE}
    networks:
      - apitable

  mysql:
    image: ${IMAGE_MYSQL}
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=${TIMEZONE}
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --sql_mode=IGNORE_SPACE,NO_ENGINE_SUBSTITUTION
      --lower_case_table_names=2
    networks:
      - apitable

  rabbitmq:
    image: ${IMAGE_RABBITMQ}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    networks:
      - apitable

  # init data
  init-db:
    image: ${IMAGE_REGISTRY}/${IMAGE_INIT_DB}
    environment:
      - TZ=${TIMEZONE}
      - DB_HOST=${MYSQL_HOST}
      - DB_PORT=${MYSQL_PORT}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USERNAME}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DATABASE_TABLE_PREFIX=${DATABASE_TABLE_PREFIX}
      - ACTION=update
    networks:
      - apitable
    deploy:
      restart_policy:
        condition: none
      replicas: 0

  # init-appdata
  init-appdata:
    image: ${IMAGE_REGISTRY}/${IMAGE_INIT_APPDATA}
    env_file:
      - "${ENV_FILE:-.env}"
    networks:
      - apitable
    deploy:
      restart_policy:
        condition: none
      replicas: 0

volumes:
  rabbitmq_data:
  mysql_data:
  redis_data:
  minio_data:
  minio_config:

networks:
  traefik:
    name: traefik_public
    external: true
  apitable:
    name: apitable_default

```
</details>

<details> <summary>Click to expand .env file </summary>

```conf
IMAGE_PULL_POLICY=always
IMAGE_REGISTRY=docker.io

IMAGE_BACKEND_SERVER=apitable/backend-server:latest
IMAGE_GATEWAY=apitable/openresty:latest
IMAGE_INIT_DB=apitable/init-db:latest
IMAGE_ROOM_SERVER=apitable/room-server:latest
IMAGE_WEB_SERVER=apitable/web-server:latest

IMAGE_DATABUS_SERVER=apitable/databus-server:latest
IMAGE_IMAGEPROXY_SERVER=apitable/imageproxy-server:latest
IMAGE_INIT_APPDATA=apitable/init-appdata:latest

IMAGE_MINIO=minio/minio:RELEASE.2023-01-25T00-19-54Z
IMAGE_MYSQL=mysql:8.0.32
IMAGE_RABBITMQ=rabbitmq:3.11.9-management
IMAGE_REDIS=redis:7.0.8

NGINX_HTTPS_PORT=443
NGINX_HTTP_PORT=80

### SERVER
BACKEND_BASE_URL=http://backend-server:8081/api/v1/
NEST_GRPC_URL=room-server:3334
SOCKET_GRPC_URL=apitable-roomserver.traefik.me:3007

### NEST CONST
OSS_CACHE_TYPE=minio
OSS_HOST=assets
OSS_TYPE=QNY1

### MINIO
MINIO_ACCESS_KEY=apitable
MINIO_SECRET_KEY=apitable@com

### MYSQL
DATABASE_TABLE_PREFIX=apitable_
MYSQL_DATABASE=apitable
MYSQL_HOST=mysql
MYSQL_PASSWORD=apitable@com
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD=apitable@com
MYSQL_USERNAME=root

### init-db
DB_HOST=mysql
DB_NAME=apitable
DB_PASSWORD=apitable@com
DB_PORT=3306
DB_USERNAME=root

### REDIS
REDIS_DB=0
REDIS_HOST=redis
REDIS_PASSWORD=apitable@com
REDIS_PORT=6379

### RabbitMQ
RABBITMQ_HOST=rabbitmq
RABBITMQ_PASSWORD=apitable@com
RABBITMQ_PORT=5672
RABBITMQ_USERNAME=apitable
RABBITMQ_VHOST=/

TIMEZONE=Asia/Singapore

ENV=apitable

API_PROXY=http://backend-server:8081
BACKEND_INFO_URL=http://backend-server:8081/api/v1/client/info
PUBLIC_URL=
TEMPLATE_PATH=./static/web_build/index.html
USE_CUSTOM_PUBLIC_FILES=true

NEST_GRPC_ADDRESS=static://room-server:3334

### apitable const
CALLBACK_DOMAIN=
CORS_ORIGINS=*
SERVER_DOMAIN=
SOCKET_DOMAIN=https://apitable-roomserver.traefik.me:3333/socket

SKIP_REGISTER_VALIDATE=true
TEMPLATE_SPACE=spcNTxlv8Drra

### apitable starter
SOCKET_RECONNECTION_ATTEMPTS=10
SOCKET_RECONNECTION_DELAY=500
SOCKET_TIMEOUT=5000
SOCKET_URL=https://apitable-roomserver.traefik.me:3002

SMS_ENABLED=false

MAIL_ENABLED=false
MAIL_FROM=
MAIL_HOST=
MAIL_PASSWORD=
MAIL_PORT=
MAIL_SSL_ENABLE=true
MAIL_TYPE=smtp
MAIL_USERNAME=

OSS_CLIENT_TYPE=aws
OSS_ENABLED=true

AWS_ACCESS_KEY=apitable
AWS_ACCESS_SECRET=apitable@com
AWS_ENDPOINT=http://minio:9000
AWS_REGION=us-east-1

HUAWEICLOUD_OBS_ACCESS_KEY=apitable
HUAWEICLOUD_OBS_ENDPOINT=obs.cn-south-1.myhuaweicloud.com
HUAWEICLOUD_OBS_SECRET_KEY=apitable@com

ASSETS_BUCKET=assets
ASSETS_URL=assets
OSS_BUCKET_NAME=assets

DATA_PATH=.

USE_NATIVE_MODULE=0
```  

</details>
