### ISSUE TITLE
fix: Room server memory leak and temporary fix

### ISSUE THREAD

**Issue by dominik-mukrecki** [apitable/apitable#315]
**Describe the bug**

It seems that room server leaks memory.
![image](https://user-images.githubusercontent.com/64379788/217084400-c6cb1d3c-12d4-47ed-8655-e476248dd911.png)

The four processes above (VM has four cores) increase memory usage over time - I experienced draining out whole RAM and swap. 

**To Reproduce**

Use API:

1. GET request with filtering and returning one row from the datasheet - 5 col x 6,5 k rows.
2. GET request with another filtering and return a few rows (depends on filter results) - 1 col x 16 k rows.
3. PATCH request - update one field in one row from the set mentioned in 1.

**Expected behavior**

Memory should be released as fast as possible to avoid leakage in production.

**Desktop (please complete the following information):**

### VPS

```
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

**Additional context**

```
  room-server:
    deploy:
      resources:
        limits:
          memory: 4096M
    image: ${IMAGE_REGISTRY}/${IMAGE_ROOM_SERVER}
    pull_policy: ${IMAGE_PULL_POLICY:-if_not_present}
    restart: always
    expose:
      - "3333"
      - "3334"
    env_file:
      - "${ENV_FILE:-.env}"
    environment:
      - NODE_ENV=${ENV}
      - NODE_OPTIONS=--max-old-space-size=2048 --max-http-header-size=80000
      - API_MAX_MODIFY_RECORD_COUNTS=${API_MAX_MODIFY_RECORD_COUNTS:-30}
      - INSTANCE_MAX_MEMORY=4096M
    networks:
      - apitable
    depends_on:
      mysql:
        condition: service_healthy
```

The content above is the fragment from `docker-compose.yaml` and there is my own fix - deploy with memory limit.

**Comment by showlovetommy** [comment]
I met this problem as well. 
I follow [Developer Guide](https://github.com/apitable/apitable/blob/develop/docs/contribute/developer-guide.md) to build my develop env.
After use commands below:
``` cmd
make run 1
make run 2
make run 3
make run 4
```
Cpu and RAM go above and beyond 99%!
OS: Ubuntu 22.04
RAM: 16 Gi

**Comment by yort-feng** [comment]
@showlovetommy @dominikmukrecki Could you please show us the result of the 'top' command while the RAM usage reached over 80%?

**Comment by yort-feng** [comment]
> 

Thanks for your detailed reply. 

Increasing memory usage over time is normal, and it could never be used over 4GB in the `room-server` which we can see from the `INSTANCE_MAX_MEMORY` environment variable.

The statement "Memory should be released as fast as possible to avoid leakage in production" is not accurate. We can refer to V8's memory collection mechanism, where GC can block the program, so the frequency of the `old-generation` collection is relatively low. At the same time, we have also set `max-old-space-size` to 2GB to prevent the old generation from taking up too much memory.

**Comment by yort-feng** [comment]
> **Describe the bug**
> 
> It seems that room server leaks memory. ![image](https://user-images.githubusercontent.com/64379788/217084400-c6cb1d3c-12d4-47ed-8655-e476248dd911.png)
> 
> The four processes above (VM has four cores) increase memory usage over time - I experienced draining out whole RAM and swap.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> Use API:
> 
> 1. GET request with filtering and returning one row from the datasheet - 5 col x 6,5 k rows.
> 2. GET request with another filtering and return a few rows (depends on filter results) - 1 col x 16 k rows.
> 3. PATCH request - update one field in one row from the set mentioned in 1.
> 
> **Expected behavior**
> 
> Memory should be released as fast as possible to avoid leakage in production.
> 
> **Desktop (please complete the following information):**
> 
> ### VPS
> ```
> NAME="Ubuntu"
> VERSION="20.04.5 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 20.04.5 LTS"
> VERSION_ID="20.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=focal
> UBUNTU_CODENAME=focal
> ```
> 
> **Additional context**
> 
> ```
>   room-server:
>     deploy:
>       resources:
>         limits:
>           memory: 4096M
>     image: ${IMAGE_REGISTRY}/${IMAGE_ROOM_SERVER}
>     pull_policy: ${IMAGE_PULL_POLICY:-if_not_present}
>     restart: always
>     expose:
>       - "3333"
>       - "3334"
>     env_file:
>       - "${ENV_FILE:-.env}"
>     environment:
>       - NODE_ENV=${ENV}
>       - NODE_OPTIONS=--max-old-space-size=2048 --max-http-header-size=80000
>       - API_MAX_MODIFY_RECORD_COUNTS=${API_MAX_MODIFY_RECORD_COUNTS:-30}
>       - INSTANCE_MAX_MEMORY=4096M
>     networks:
>       - apitable
>     depends_on:
>       mysql:
>         condition: service_healthy
> ```
> 
> The content above is the fragment from `docker-compose.yaml` and there is my own fix - deploy with memory limit.

@dominikmukrecki Thanks for your detailed report. 

Increasing memory usage over time is normal, and it could never be used over 4GB in the `room-server` which we can see from the `INSTANCE_MAX_MEMORY` environment variable.

The statement "Memory should be released as fast as possible to avoid leakage in production" is not accurate. We can refer to V8's memory collection mechanism, where GC can block the program, so the frequency of the `old-generation` collection is relatively low. At the same time, we have also set `max-old-space-size` to 2GB to prevent the old generation from taking up too much memory.

**Comment by dominik-mukrecki** [comment]
Hello,

![image](https://user-images.githubusercontent.com/64379788/217210716-7e209867-6154-4a92-b1a7-68e951eabf82.png)

_@showlovetommy @dominikmukrecki Could you please show us the result of the 'top' command while the RAM usage reached over 80%?_

I have to limit resources due to deploying APITable in the cloud - currently memory limited to 5G with `deploy`, but even with `INSTANCE_MAX_MEMORY=4096M` 4G limit is exceeded up to 5G.

```
  room-server:
    deploy:
      resources:
        limits:
          memory: 5120M
    image: ${IMAGE_REGISTRY}/${IMAGE_ROOM_SERVER}
    pull_policy: ${IMAGE_PULL_POLICY:-if_not_present}
    restart: always
    expose:
      - "3333"
      - "3334"
    env_file:
      - "${ENV_FILE:-.env}"
    environment:
      - NODE_ENV=${ENV}
      - NODE_OPTIONS=--max-old-space-size=2048 --max-http-header-size=80000
      - API_MAX_MODIFY_RECORD_COUNTS=${API_MAX_MODIFY_RECORD_COUNTS:-30}
      - INSTANCE_MAX_MEMORY=4096M
    networks:
      - apitable
    depends_on:
      mysql:
        condition: service_healthy

```

It seems like `INSTANCE_MAX_MEMORY=4096M` is somehow bypassed.

_The statement "Memory should be released as fast as possible to avoid leakage in production" is not accurate._

Sorry for the inconvenience, you are obviously right. I am testing software as a business stack creator rather than a developer.

**Comment by dominikmukrecki** [comment]
Hello,

![image](https://user-images.githubusercontent.com/64379788/217210716-7e209867-6154-4a92-b1a7-68e951eabf82.png)

_@showlovetommy @dominikmukrecki Could you please show us the result of the 'top' command while the RAM usage reached over 80%?_

I have to limit resources due to deploying APITable in the cloud - currently memory limited to 5G with `deploy`, but even with `INSTANCE_MAX_MEMORY=4096M` 4G limit is exceeded up to 5G.

```
  room-server:
    deploy:
      resources:
        limits:
          memory: 5120M
    image: ${IMAGE_REGISTRY}/${IMAGE_ROOM_SERVER}
    pull_policy: ${IMAGE_PULL_POLICY:-if_not_present}
    restart: always
    expose:
      - "3333"
      - "3334"
    env_file:
      - "${ENV_FILE:-.env}"
    environment:
      - NODE_ENV=${ENV}
      - NODE_OPTIONS=--max-old-space-size=2048 --max-http-header-size=80000
      - API_MAX_MODIFY_RECORD_COUNTS=${API_MAX_MODIFY_RECORD_COUNTS:-30}
      - INSTANCE_MAX_MEMORY=4096M
    networks:
      - apitable
    depends_on:
      mysql:
        condition: service_healthy

```

It seems like `INSTANCE_MAX_MEMORY=4096M` is somehow bypassed.

_The statement "Memory should be released as fast as possible to avoid leakage in production" is not accurate._

Sorry for inconvinience
