### ISSUE TITLE
question: healthcheck for room-server

### ISSUE THREAD

**Issue by grigorev-lm** [apitable/apitable#678]
Hello Team,
I'm deploying Apitable in k8s cluster, what is the correct away to get healthchecks for `room-server` container? If its http get probe what port should I use for it?

**Comment by yort-feng** [comment]
@grigorev-lm The below configuration is an example of a liveness probe

```
 httpGet:
          path: /actuator/health
          port: 3333
          scheme: HTTP
```
