### ISSUE TITLE
fix: Raising API Limits does not seem to work

### ISSUE THREAD

**Issue by NN-Binary** [apitable/apitable#700]
**Describe the bug**
When putting ENV variable 

**To Reproduce**
In file `docker-compose.yaml`, in `room-server`:

```
  room-server:
    image: ${IMAGE_REGISTRY}/${IMAGE_ROOM_SERVER}
    pull_policy: ${IMAGE_PULL_POLICY:-if_not_present}
    restart: always
    expose:
      - "3333"
      - "3334"
      - "3001"
      - "3002"
      - "3006"
      - "3005"
      - "3007"
    env_file:
      - "${ENV_FILE:-.env}"
    environment:
      - NODE_ENV=${ENV}
      - NODE_OPTIONS=--max-old-space-size=2048 --max-http-header-size=80000
      - API_MAX_MODIFY_RECORD_COUNTS=${API_MAX_MODIFY_RECORD_COUNTS:-30}
      - INSTANCE_MAX_MEMORY=8096M
      - ENABLE_SOCKET=true
      - LIMIT_POINTS=1000
    networks:
      - apitable
    depends_on:
      mysql:
        condition: service_healthy
```

Here, LIMIT_POINTS is specified to 10000, I've tried also 999999999 to be sure, but it does NOT change the API Limit with message: 'API requests are sent too frequently', rebooted the server to make sure changes are applied, but it does not work.

Anyway to raise the API limit?

**Expected behavior**
LIMIT_POINTS should raise API Limit
