### ISSUE TITLE
question: Health checks for webserver and backend components

### ISSUE THREAD

**Issue by grigorev-lm** [apitable/apitable#701]
Hello Team!
In one of my previous [issues](https://github.com/apitable/apitable/issues/678) I asked how to implement health checks for room-server component, now I want to set up k8s probes for webserver and backend components. So my question is what path url should I use to make k8s probes work for this components?

**Comment by yort-feng** [comment]
- backend-server's liveness probe
```
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1/actuator/health/liveness
              port: 8081
              scheme: HTTP
```
- web-server's liveness probe
```
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/actuator/health
              port: 8080
              scheme: HTTP
```
